version: "3"
services:
    postgres:
        image: postgres:latest
        container_name: database
        ports:
            - "5432:5432"
        volumes:
            - /data/postgres:/data/postgres
        env_file:
            - .env
        networks:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
          - "8080:80"
        volumes:
          - /data/pgadmin:/root/.pgadmin
        env_file:
            - .env
        links:
          - postgres:postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge