import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE tariffs (
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       percent int NOT NULL,
       to_day int NOT NULL,
       from_day int NOT NULL
    )
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
      DROP TABLE tariffs
  `);
}
